<?php

namespace App\Console\Commands;

use App\Services\Blueprint\BlueprintGenerator;
use App\Services\Blueprint\BlueprintSchema;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;

class CheckBlueprintGeneration extends Command
{
    protected $signature = 'blueprint:check
                            {--generate : Also generate a real blueprint, which costs credits}
                            {--model= : Check a different model than the configured one}';

    protected $description = 'Verify the OpenRouter key, model, and blueprint generation';

    public function handle(): int
    {
        $key = (string) config('services.openrouter.key');
        $model = (string) ($this->option('model') ?: config('services.openrouter.model'));

        $this->newLine();
        $this->line('<options=bold>Configuration</>');
        $this->line('  key      '.($key === '' ? '<fg=red>not set</>' : substr($key, 0, 8).str_repeat('*', 8).substr($key, -4)));
        $this->line('  model    '.$model);
        $this->line('  timeout  '.config('services.openrouter.timeout').'s');

        if ($key === '') {
            $this->newLine();
            $this->error('OPENROUTER_API_KEY is not set. Generation will fall back to the template.');

            return self::FAILURE;
        }

        // 1. Does the key authenticate, and does the account have anything to spend?
        $this->newLine();
        $this->line('<options=bold>Account</>');

        $auth = Http::withToken($key)->timeout(30)->get('https://openrouter.ai/api/v1/key');

        if ($auth->failed()) {
            $this->error('  Key rejected ('.$auth->status().'). Check OPENROUTER_API_KEY.');

            return self::FAILURE;
        }

        $account = $auth->json('data');
        $this->line('  <fg=green>key is valid</>');
        $this->line('  used     $'.($account['usage'] ?? 0));
        $this->line('  limit    '.(($account['limit'] ?? null) !== null ? '$'.$account['limit'] : 'none set'));

        if ($account['is_free_tier'] ?? false) {
            $this->warn('  This account is on the free tier — paid models return 402 until credits are purchased.');
        }

        // 2. Does the configured model exist, and can it honour a strict schema?
        $this->newLine();
        $this->line('<options=bold>Model</>');

        $models = collect(Http::withToken($key)->timeout(30)->get('https://openrouter.ai/api/v1/models')->json('data'));
        $found = $models->firstWhere('id', $model);

        if (! $found) {
            $this->error("  \"{$model}\" was not found on OpenRouter.");
            $this->line('  Check the slug at https://openrouter.ai/models');

            return self::FAILURE;
        }

        $supportsSchema = in_array('structured_outputs', $found['supported_parameters'] ?? [], true);
        $in = (float) ($found['pricing']['prompt'] ?? 0) * 1_000_000;
        $out = (float) ($found['pricing']['completion'] ?? 0) * 1_000_000;

        $this->line('  <fg=green>found</> '.($found['name'] ?? $model));
        $this->line('  context  '.number_format($found['context_length'] ?? 0));
        $this->line('  pricing  $'.$in.' in / $'.$out.' out per million tokens');
        $this->line('  schema   '.($supportsSchema ? '<fg=green>structured outputs supported</>' : '<fg=red>NOT supported</>'));

        // A blueprint runs roughly 900 tokens in and 3,500 out.
        if ($in > 0 || $out > 0) {
            $this->line('  est.     $'.number_format((900 * $in + 3500 * $out) / 1_000_000, 5).' per blueprint');
        }

        if (! $supportsSchema) {
            $this->warn('  Without structured outputs the response will often miss the schema and fall back.');
        }

        if (! $this->option('generate')) {
            $this->newLine();
            $this->line('Run with <options=bold>--generate</> to produce a real blueprint end to end.');
            $this->newLine();

            return self::SUCCESS;
        }

        // 3. The real thing.
        $this->newLine();
        $this->line('<options=bold>Generating</>');

        config(['services.openrouter.model' => $model]);

        $result = app(BlueprintGenerator::class)->generate([
            'brand_name' => 'Scentrism',
            'industry' => 'Fragrance',
            'audience' => 'Urban professionals, 28-45, who treat fragrance as a daily ritual.',
            'price_position' => 'Premium',
            'vision' => 'A fragrance house built around emotional wellness and mindful living.',
        ]);

        if ($result->generator !== 'openrouter') {
            $this->error('  Fell back to the template.');
            $this->line('  '.$result->failureReason);

            return self::FAILURE;
        }

        $this->line('  <fg=green>generated by the model</> in '.number_format((int) $result->generationMs).' ms');
        $this->line('  schema   '.(BlueprintSchema::validate($result->payload) ?? '<fg=green>valid</>'));
        $this->newLine();
        $this->line('  tagline  '.$result->payload['tagline']);
        $this->line('  scores   brand '.$result->payload['scores']['brand']
            .' / market '.$result->payload['scores']['market']
            .' / growth '.$result->payload['scores']['growth']);
        $this->newLine();

        return self::SUCCESS;
    }
}
