<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('brand_blueprints', function (Blueprint $table) {
            $table->id();
            $table->uuid()->unique();

            // Set once members can sign in; blueprints are generated by guests today.
            $table->foreignId('member_id')->nullable()->constrained()->nullOnDelete();

            $table->string('brand_name');
            $table->string('industry');
            $table->text('audience');
            $table->string('price_position');
            $table->text('vision');

            // The generated blueprint itself, so a result page can be revisited as issued.
            $table->json('payload');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('brand_blueprints');
    }
};
