<x-webcms.layout
    title="Brand Blueprints"
    heading="Brand Blueprints"
    subheading="Every blueprint members have generated."
>
    @php
        $tiles = [
            ['label' => 'Total', 'value' => $stats['total'], 'icon' => 'sparkles'],
            ['label' => 'Generated by AI', 'value' => $stats['ai'], 'icon' => 'circle-check'],
            ['label' => 'Fell back to template', 'value' => $stats['fallback'], 'icon' => 'circle-alert'],
        ];
    @endphp

    <div class="grid gap-4 sm:grid-cols-3">
        @foreach ($tiles as $tile)
            <x-webcms.card class="p-5">
                <div class="flex items-start justify-between gap-3">
                    <p class="text-xs uppercase tracking-wide text-ink/50">{{ $tile['label'] }}</p>
                    <span class="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-steel/70 text-navy/60">
                        <i data-lucide="{{ $tile['icon'] }}" class="h-4 w-4"></i>
                    </span>
                </div>
                <p class="mt-3 text-3xl font-semibold tracking-tight text-navy">
                    {{ number_format($tile['value']) }}
                </p>
            </x-webcms.card>
        @endforeach
    </div>

    <x-webcms.card class="mt-6">
        <div class="flex flex-wrap items-center justify-between gap-3 border-b border-border/70 px-6 py-4">
            <form method="GET" action="{{ route('webcms.brand-blueprints.index') }}" class="relative w-full max-w-sm">
                <i data-lucide="search" class="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-ink/40"></i>
                <input
                    type="search"
                    name="search"
                    value="{{ $search }}"
                    placeholder="Search brand, industry, or audience"
                    class="w-full rounded-full border border-navy/15 bg-white py-2.5 pl-10 pr-4 text-sm text-navy outline-none transition-colors placeholder:text-ink/40 focus:border-navy focus:ring-2 focus:ring-navy/10"
                />
            </form>

            <p class="text-sm text-ink/50">{{ number_format($blueprints->total()) }} total</p>
        </div>

        @if ($blueprints->isEmpty())
            <x-webcms.empty-state icon="sparkles" :title="$search ? 'No blueprints match your search' : 'No blueprints yet'">
                {{ $search ? 'Try a different brand, industry, or audience.' : 'Blueprints appear here as members generate them.' }}
            </x-webcms.empty-state>
        @else
            <div class="overflow-x-auto">
                <table class="w-full text-left text-sm">
                    <thead>
                        <tr class="border-b border-border/70 text-xs uppercase tracking-wide text-ink/50">
                            <th scope="col" class="px-6 py-3 font-medium">Brand</th>
                            <th scope="col" class="px-6 py-3 font-medium">Member</th>
                            <th scope="col" class="px-6 py-3 font-medium">Position</th>
                            <th scope="col" class="px-6 py-3 font-medium">Source</th>
                            <th scope="col" class="px-6 py-3 font-medium">Generated</th>
                            <th scope="col" class="px-6 py-3 text-right font-medium">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-border/70">
                        @foreach ($blueprints as $blueprint)
                            <tr class="transition-colors hover:bg-steel/25">
                                <td class="px-6 py-4">
                                    <a href="{{ route('webcms.brand-blueprints.show', $blueprint) }}" class="block min-w-0">
                                        <p class="truncate font-medium text-navy">{{ $blueprint->brand_name }}</p>
                                        <p class="truncate text-xs text-ink/50">{{ $blueprint->industry }}</p>
                                    </a>
                                </td>
                                <td class="px-6 py-4">
                                    @if ($blueprint->member)
                                        <p class="truncate text-navy">{{ $blueprint->member->name }}</p>
                                        <p class="truncate text-xs text-ink/50">{{ $blueprint->member->email }}</p>
                                    @else
                                        <span class="text-ink/40">Guest</span>
                                    @endif
                                </td>
                                <td class="whitespace-nowrap px-6 py-4 text-ink/70">{{ $blueprint->price_position }}</td>
                                <td class="px-6 py-4">
                                    <x-webcms.badge :active="$blueprint->wasGeneratedByAi()">
                                        {{ $blueprint->wasGeneratedByAi() ? 'AI' : 'Template' }}
                                    </x-webcms.badge>
                                </td>
                                <td class="whitespace-nowrap px-6 py-4 text-ink/60">
                                    {{ $blueprint->created_at->format('d M Y') }}
                                </td>
                                <td class="px-6 py-4">
                                    <div class="flex items-center justify-end gap-1">
                                        <a
                                            href="{{ route('webcms.brand-blueprints.show', $blueprint) }}"
                                            class="grid h-9 w-9 place-items-center rounded-lg text-ink/50 transition-colors hover:bg-steel/60 hover:text-navy"
                                            aria-label="View {{ $blueprint->brand_name }}"
                                        >
                                            <i data-lucide="eye" class="h-4 w-4"></i>
                                        </a>

                                        <form
                                            method="POST"
                                            action="{{ route('webcms.brand-blueprints.destroy', $blueprint) }}"
                                            data-confirm="Delete the blueprint for {{ $blueprint->brand_name }}? This cannot be undone."
                                        >
                                            @csrf
                                            @method('DELETE')
                                            <button
                                                type="submit"
                                                class="grid h-9 w-9 place-items-center rounded-lg text-ink/50 transition-colors hover:bg-danger/10 hover:text-danger"
                                                aria-label="Delete {{ $blueprint->brand_name }}"
                                            >
                                                <i data-lucide="trash-2" class="h-4 w-4"></i>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            @if ($blueprints->hasPages())
                <div class="border-t border-border/70 px-6 py-4">
                    {{ $blueprints->links('webcms.pagination') }}
                </div>
            @endif
        @endif
    </x-webcms.card>
</x-webcms.layout>
