<x-site.layout
    :title="$bp['brand_name'].' — Brand Blueprint™ by Visionyr'"
    :description="$bp['tagline']"
    nav="minimal"
    :footer="false"
>
    <div class="relative">
        <div class="absolute inset-0 grid-bg opacity-50" aria-hidden="true"></div>
        <div class="pointer-events-none absolute inset-x-0 top-0 h-[420px] bg-gradient-to-b from-steel/40 to-transparent" aria-hidden="true"></div>

        <div class="relative mx-auto max-w-5xl px-6 pb-24 pt-14 animate-rise lg:pt-20">

            {{-- ===== HEADER ===== --}}
            <div class="flex flex-wrap items-end justify-between gap-6">
                <div class="max-w-2xl">
                    <div class="inline-flex items-center gap-2 rounded-full border border-navy/10 bg-white/70 px-3 py-1.5 text-xs text-navy/80 shadow-soft">
                        <i data-lucide="sparkles" class="h-3 w-3 text-navy"></i>
                        Brand Blueprint&trade; &middot; Generated by Visionyr
                    </div>

                    <h1 class="mt-5 text-balance text-4xl font-semibold tracking-[-0.02em] text-navy md:text-5xl">
                        {{ $bp['brand_name'] }}
                    </h1>
                    <p class="mt-3 text-pretty text-lg text-ink/70">{{ $bp['tagline'] }}</p>

                    <div class="mt-4 flex flex-wrap gap-2 text-xs">
                        @foreach ($bp['chips'] as $chip)
                            <span class="inline-flex items-center rounded-full border border-navy/10 bg-white px-2.5 py-1 text-xs font-medium text-navy/80">
                                {{ $chip }}
                            </span>
                        @endforeach
                    </div>
                </div>

                <div class="flex flex-wrap gap-2">
                    <a href="{{ route('blueprint.create') }}" class="inline-flex items-center gap-1.5 rounded-full border border-navy/15 bg-white px-4 py-2.5 text-sm font-medium text-navy transition-colors hover:bg-steel/40">
                        <i data-lucide="refresh-cw" class="h-3.5 w-3.5"></i> Generate Another Blueprint
                    </a>

                    <button type="button" disabled title="Coming soon" class="inline-flex cursor-not-allowed items-center gap-1.5 rounded-full border border-navy/15 bg-white px-4 py-2.5 text-sm font-medium text-navy/60">
                        <i data-lucide="download" class="h-3.5 w-3.5"></i> Download PDF
                        <span class="ml-1 rounded-full bg-steel/60 px-1.5 py-0.5 text-[10px] uppercase tracking-wide text-navy/70">Soon</span>
                    </button>

                    <a href="{{ route('home') }}#pricing" class="inline-flex items-center gap-1.5 rounded-full bg-navy px-4 py-2.5 text-sm font-medium text-white transition-all hover:bg-navy/90 hover:shadow-glow">
                        <i data-lucide="crown" class="h-3.5 w-3.5 text-mint"></i> Upgrade to Builder
                    </a>
                </div>
            </div>

            {{-- ===== SCORES ===== --}}
            @php
                $scores = [
                    ['label' => 'Brand Score', 'value' => $bp['scores']['brand'], 'dot' => 'bg-navy'],
                    ['label' => 'Market Fit', 'value' => $bp['scores']['market'], 'dot' => 'bg-mint'],
                    ['label' => 'Growth Potential', 'value' => $bp['scores']['growth'], 'dot' => 'bg-steel'],
                ];
            @endphp

            <div class="mt-10 grid gap-4 md:grid-cols-3">
                @foreach ($scores as $score)
                    <div class="rounded-2xl border border-navy/10 bg-white p-5 shadow-soft">
                        <div class="flex items-center justify-between">
                            <p class="text-xs uppercase tracking-wide text-ink/50">{{ $score['label'] }}</p>
                            <span class="h-2 w-2 rounded-full {{ $score['dot'] }}"></span>
                        </div>
                        <p class="mt-3 text-3xl font-semibold tracking-tight text-navy">{{ $score['value'] }}%</p>
                        <div class="mt-3 h-1 w-full overflow-hidden rounded-full bg-navy/10">
                            <div class="h-full rounded-full bg-navy" style="width:{{ $score['value'] }}%"></div>
                        </div>
                    </div>
                @endforeach
            </div>

            {{-- ===== BLUEPRINT ===== --}}
            <div class="mt-6 grid gap-5 lg:grid-cols-3">

                <x-site.blueprint-card icon="trending-up" title="Market Opportunity" class="lg:col-span-2">
                    <p class="text-ink/75">{{ $bp['market_opportunity'] }}</p>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="target" title="Brand Positioning">
                    <p class="text-ink/75">{{ $bp['positioning'] }}</p>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="users" title="Target Audience">
                    <ul class="space-y-2.5 text-ink/75">
                        @foreach ($bp['audience'] as $line)
                            <li class="flex gap-2">
                                <i data-lucide="check" class="mt-1 h-3.5 w-3.5 shrink-0 text-navy"></i>
                                <span>{{ $line }}</span>
                            </li>
                        @endforeach
                    </ul>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="heart" title="Brand Personality">
                    <div class="flex flex-wrap gap-2">
                        @foreach ($bp['personality'] as $trait)
                            <span class="inline-flex items-center rounded-full border border-navy/10 bg-white px-2.5 py-1 text-xs font-medium text-navy/80">
                                {{ $trait }}
                            </span>
                        @endforeach
                    </div>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="compass" title="Brand Values">
                    <ul class="space-y-2.5 text-ink/75">
                        @foreach ($bp['values'] as $value)
                            <li>
                                <p class="font-medium text-navy">{{ $value['title'] }}</p>
                                <p class="text-sm text-ink/65">{{ $value['desc'] }}</p>
                            </li>
                        @endforeach
                    </ul>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="book-open" title="Brand Story" class="lg:col-span-2">
                    <p class="whitespace-pre-line text-ink/75">{{ $bp['story'] }}</p>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="mic" title="Brand Voice">
                    <ul class="space-y-2.5 text-ink/75">
                        @foreach ($bp['voice'] as $voice)
                            <li>
                                <p class="font-medium text-navy">{{ $voice['title'] }}</p>
                                <p class="text-sm text-ink/65">{{ $voice['desc'] }}</p>
                            </li>
                        @endforeach
                    </ul>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="type" title="Naming Recommendations">
                    <ul class="space-y-2 text-ink/75">
                        @foreach ($bp['naming'] as $name)
                            <li class="flex items-center justify-between rounded-lg border border-navy/10 bg-steel/20 px-3 py-2">
                                <span class="font-medium text-navy">{{ $name }}</span>
                                <span class="text-xs text-ink/50">.co</span>
                            </li>
                        @endforeach
                    </ul>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="tag" title="Tagline Ideas">
                    <ul class="space-y-2 text-ink/75">
                        @foreach ($bp['taglines'] as $tagline)
                            <li class="rounded-lg border border-navy/10 bg-white px-3 py-2 text-sm">{{ $tagline }}</li>
                        @endforeach
                    </ul>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="palette" title="Visual Direction">
                    <ul class="space-y-2.5 text-ink/75">
                        @foreach ($bp['visual'] as $visual)
                            <li>
                                <p class="font-medium text-navy">{{ $visual['title'] }}</p>
                                <p class="text-sm text-ink/65">{{ $visual['desc'] }}</p>
                            </li>
                        @endforeach
                    </ul>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="palette" title="Color Direction" class="lg:col-span-2">
                    <div class="grid grid-cols-2 gap-3 md:grid-cols-5">
                        @foreach ($bp['colors'] as $color)
                            <div class="overflow-hidden rounded-xl border border-navy/10">
                                <div class="h-20 w-full" style="background:{{ $color['hex'] }}"></div>
                                <div class="bg-white px-3 py-2">
                                    <p class="text-sm font-medium text-navy">{{ $color['name'] }}</p>
                                    <p class="text-xs uppercase tracking-wide text-ink/50">{{ $color['hex'] }}</p>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="rocket" title="Launch Strategy" class="lg:col-span-2">
                    <ol class="space-y-3 text-ink/75">
                        @foreach ($bp['launch'] as $index => $phase)
                            <li class="flex gap-3">
                                <span class="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-navy text-xs font-medium text-white">
                                    {{ $index + 1 }}
                                </span>
                                <div>
                                    <p class="font-medium text-navy">{{ $phase['title'] }}</p>
                                    <p class="text-sm text-ink/65">{{ $phase['desc'] }}</p>
                                </div>
                            </li>
                        @endforeach
                    </ol>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="layers" title="Content Pillars">
                    <ul class="space-y-2 text-ink/75">
                        @foreach ($bp['pillars'] as $pillar)
                            <li class="flex items-start gap-2">
                                <span class="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-navy"></span>
                                <span>{{ $pillar }}</span>
                            </li>
                        @endforeach
                    </ul>
                </x-site.blueprint-card>

                <x-site.blueprint-card icon="calendar-days" title="First 30-Day Action Plan" class="lg:col-span-3">
                    <div class="grid gap-4 md:grid-cols-4">
                        @foreach ($bp['plan'] as $week)
                            <div class="rounded-2xl border border-navy/10 bg-steel/20 p-5">
                                <p class="text-xs uppercase tracking-wide text-ink/50">{{ $week['week'] }}</p>
                                <p class="mt-1 font-medium text-navy">{{ $week['title'] }}</p>
                                <ul class="mt-3 space-y-2 text-sm text-ink/70">
                                    @foreach ($week['items'] as $item)
                                        <li class="flex items-start gap-2">
                                            <i data-lucide="check" class="mt-0.5 h-3.5 w-3.5 shrink-0 text-navy"></i>
                                            <span>{{ $item }}</span>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                        @endforeach
                    </div>
                </x-site.blueprint-card>

            </div>

            {{-- ===== UPSELL ===== --}}
            <div class="mt-10 overflow-hidden rounded-3xl border border-navy/10 bg-navy p-8 text-white shadow-card md:p-12">
                <div class="flex flex-wrap items-center justify-between gap-6">
                    <div class="max-w-xl">
                        <p class="text-xs uppercase tracking-wide text-mint">Visionyr Builder</p>
                        <h3 class="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">
                            Turn this Blueprint into a brand you can launch.
                        </h3>
                        <p class="mt-3 text-white/70">
                            Upgrade to Builder to unlock the full identity system, brand guidelines, launch campaigns,
                            and a 90-day growth plan.
                        </p>
                    </div>

                    <div class="flex flex-wrap gap-2">
                        <a href="{{ route('blueprint.create') }}" class="inline-flex items-center gap-1.5 rounded-full border border-white/20 px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-white/10">
                            <i data-lucide="refresh-cw" class="h-3.5 w-3.5"></i> Generate Another
                        </a>
                        <a href="{{ route('home') }}#pricing" class="inline-flex items-center gap-1.5 rounded-full bg-mint px-5 py-2.5 text-sm font-medium text-navy transition-colors hover:bg-white">
                            <i data-lucide="crown" class="h-3.5 w-3.5"></i> Upgrade to Builder
                            <i data-lucide="arrow-right" class="h-3.5 w-3.5"></i>
                        </a>
                    </div>
                </div>
            </div>

            <p class="mt-8 text-center text-xs text-ink/50">
                Blueprint generated {{ $blueprint->created_at->diffForHumans() }} &middot; keep this link to come back to it.
            </p>

        </div>
    </div>
</x-site.layout>
